title: UNCA Live Updates
default_author: United Nations Correspondants Association
future: true
description: Live updates from the United Nations Correspondants Association

collections:
  posts:
    output: true
    permalink: /:collection/:name

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

plugins:
  - jekyll-feed
